In [12]:
sample_size = 13
batch_size = 13
import math
import numpy as np

data = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24],
    [25, 26, 27, 28],
    [29, 30, 31, 32],
    [33, 34, 35, 36],
    [37, 38, 39, 40],
    [41, 42, 43, 44],
    [45, 46, 47, 48],
    [49, 50, 51, 52]
])

for idx in range(math.ceil(sample_size / batch_size)):
    batch_data = data[idx*batch_size:(idx+1)*batch_size,:]
    print(batch_data)
    print("-"*50)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]
 [49 50 51 52]]
--------------------------------------------------
